yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView, \
    PasswordResetView, PasswordChangeDoneView, \
    PasswordResetDoneView, PasswordResetCompleteView, PasswordChangeView, \
    PasswordResetCompleteView

from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('password_reset/',
         PasswordResetView.as_view
         (template_name='users/password_reset_form.html'),
         name='password_reset_form'),
    path('password_change/',
         PasswordChangeView.as_view
         (template_name='users/password_change_form.html'),
         name='password_change_form'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view
         (template_name='users/password_change_done.html',),
         name='password_change_done'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view
         (template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/done/',
         PasswordResetCompleteView.as_view
         (template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('reset/<uidb64>/<token>/',
         PasswordResetCompleteView.as_view
         (template_name='users/password_reset_confirm.html')),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/about/models.py
# from django.db import models

# Create your models here.

yatube/posts/models.py
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(unique=True,
                            verbose_name='Адрес группы типа slug')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста',
                            help_text='Введите текст поста'
                            )
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]

yatube/users/models.py
# from django.db import models

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {'text': 'Текст публикации', 'group': 'Группа'}
        help_texts = {
            'group': 'Группа, к которой будет относиться пост',
            'text': 'Tекст нового поста'
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
# from django.shortcuts import render
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from .models import Post, Group, User
from .forms import PostForm

from django.conf import settings


def pagination(request, post_objs):
    paginator = Paginator(post_objs, settings.POSTS_SHOWN)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    posts = Post.objects.select_related('group').all()
    page_obj = pagination(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = pagination(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    page_obj = pagination(request, author.posts.all())
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    # Обращение через related_name, чтобы не иcпользовать фильтр
    posts_per_auth = post.author.posts.count()
    context = {
        'post': post,
        'posts_per_auth': posts_per_auth,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post.id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.id)
    return render(request, 'posts/create_post.html', {'form': form,
                                                      'post': post,
                                                      'is_edit': True})

yatube/users/views.py
# from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block main%}
<div class="container  py-5">
<h1>Привет, меня зовут Анна, я автор этого проекта!</h1>

<div class="row">
  <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6"> 
<p>
Программирование - новое неожиданное для меня открытие. 
Почти всю жизнь считала себя законченным гуманитарием, 
но потом пришло понимание, что такие ярлыки развешивать не стоит, 
новые грани себя могут открыться весьма неожиданно. 
Так я и открыла для себя совершенно чудесный новый мир - 
программирование. Порой бывает сложно, но от этого только интереснее. 
Это мой первый проект, HTML, признаюсь честно, знаю пока плоховато, потому эта страничка такая неказистая. 
Гарантирую, скоро это исправится;)
И раз пока я еще не подобрала годный контент,
предлагаю посмотреть, в каком формате частенько проходит мой учебный процесс. 
</p>
</div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
  <img src="/static/img/workspace.jpg" height="400" class="d-inline-block align-top" alt="Котик-помощник" title="Куда же без помощников)))">
</div>

  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2>Мои контакты</h2>
    </div>
  </div>
</div>
<p></p>
<div class="container">
  <div class="row">
    <div class="col-12">
      <p>Почта: <a href="mailto: zebra9999@rambler.ru">zebra9999@rambler.ru</a></p>
      <p>Github: <a href="https://github.com/ZebraHr">github.com/ZebraHr</a></p>
    </div>
  </div>
</div>



{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block main %}
<div class="container py-5">
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот, что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
      <li class="list-group-item">
        HTML
      </li>
      <li class="list-group-item">
        SQLite
      </li>
      <li class="list-group-item">
        Git
      </li>
      <li class="list-group-item">
        GitHub
      </li>
      <li class="list-group-item">
        CSS
      </li>      
      <li class="list-group-item">
        Bootstrap
      </li>      

    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Список будет пополняться, следите за обновлениями :)</p>
  </article>
</div>
</div>
{% endblock %} 

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% load static %}
<html lang="ru"> <!-- Язык сайта - русский -->

  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <title>
      {% block title %}
      {% endblock title %}
    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html'%}

    </header>
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      {% block main %}
      {% endblock main %}
    </main>
    <footer class="page-footer font-small blue border-top">
      {% include 'includes/footer.html'%}    
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<!DOCTYPE html>
<div class="footer-copyright text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
  </div>

yatube/templates/includes/header.html
<!DOCTYPE html>
{% load static %}
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <span style="color:red">Ya</span>tube
        </a>
        {# Добавлено в спринте #}
  
        {% comment %}
        Меню - список пунктов со стандартными классами Bootsrap.
        Класс nav-pills нужен для выделения активных пунктов 
        {% endcomment %}
        {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
           href="{% url 'about:author' %}">Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
            href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" 
            href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:password_change_form' %}active{% endif %}" 
            href="{% url 'users:password_change_form' %}">Изменить пароль</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" 
            href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li> 
            Пользователь: {{ user.username }}
          </li>
          {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" 
            href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" 
            href="{% url 'users:signup' %}">Регистрация</a>
          </li>
          {% endif %}
        </ul>
        {% endwith %} 
        {# Конец добавленого в спринте #}
      </div>
    </nav>      
  </header> 

yatube/templates/includes/paginator.html
{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}
 

yatube/templates/posts/create_post.html
<!DOCTYPE html>
{% extends 'base.html'%}

{% block title %}
{% if is_edit %}
Редктировать пост
{% else %}
Новый пост
{% endif %} 
{% endblock title %}

{% block main %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">      
            {% if is_edit %}
            Редктировать пост
          {% else %}
            Новый пост
          {% endif %}  

          </div>
          <div class="card-body">   
            {% load user_filters %}     
            <form method="post" 
            action={% if post %}"{% url 'posts:post_edit' post_id=post.id %}"{% else %}"{% url 'posts:post_create' %}"{% endif %}>
                {% csrf_token %}          
                {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
                    
              {% endfor %}

              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %} 
              </button>
        
            </form>
        </div>
      </div>
    </div>
  </div>
</div>
              {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html'%}

{% block title %}
Записи группы {{ group }}
  {% endblock title %}

{% block main %}
<div class="container py-5">
  <h1>{{group}}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>   
  <a href="{% url 'posts:post_detail' post.id  %}">подробная информация</a><br>
  {% if post.group %}   
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %} 
    {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 

</div>  
{% include 'includes/paginator.html' %}
{% endblock main %}

yatube/templates/posts/index.html
<!DOCTYPE html>
{% extends 'base.html'%}

{% block title %}
Последние обновления на сайте
{% endblock title %}


{% block main %}
<div class="container py-5">
  
  <article>
    <h1> Последние обновления на сайте </h1>
    {% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}              
      <a href="{% url 'posts:profile' post.author.username %}">
        все посты пользователя
      </a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>   
  <a href="{% url 'posts:post_detail' post.id  %}">подробная информация</a><br>
    {% if post.group %}   
   <a href="{% url 'posts:group_list' post.group.slug  %}">все записи группы {{ post.group }}</a>
   {% endif %} 
    {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 

{% include 'includes/paginator.html' %}
  <!-- под последним постом нет линии -->
</div>  
{% endblock main %}

yatube/templates/posts/post_detail.html
<!DOCTYPE html>
{% extends 'base.html'%}

{% block title %}
Пост {{ post.text|truncatechars:30 }}
{% endblock title %}

{% block main %}
<div class="container py-5">
      <div class="row">
        <aside class="col-12 col-md-3">
         <ul class="list-group list-group-flush">

            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group }}<br>
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            </li>
            {% endif %} 
            <li class="list-group-item">
              
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ posts_per_auth }}</span>
            </li>
            <li class="list-group-item">
             <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>

                </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
         {{ post.text }}
          </p>
          
          {% if post.author == request.user %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
                редактировать запись
              </a>
            {% endif %}
        </article>
      </div> 
    </div>
</main>
      {% endblock main %}

yatube/templates/posts/profile.html
<!DOCTYPE html>
{% extends 'base.html'%}

{% block title %}
    Профайл пользователя {{ author.get_full_name }}
{% endblock title %}
     
{% block main %}
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>   
        <article>
            {% for post in page_obj %}
            <ul>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
               
                    {% if post.group %} 
                    <li>
                    Группа: {{ post.group }}
                  </li>
                    {% endif %} 
                
              </ul>
              <p>{{ post.text|linebreaks  }}</p>   
  
            <a href="{% url 'posts:post_detail' post.id  %}">Подробная информация</a>

                {% if post.group %}   
            </article> 
               <p><a href="{% url 'posts:group_list' post.group.slug  %}">Все записи группы {{ post.group }}</a></p>
               {% endif %} 
                {% if not forloop.last %}<hr>{% endif %}
            {% endfor %} 
        </article>       
        {% include 'includes/paginator.html' %}
      </div>

      {% endblock main %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block main %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block main %}
{% load user_filters %}
<div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Изменить пароль
          </div>
          <div class="card-body"> 
            <form method="post" action="{% url 'users:password_change_form' %}">
              {% csrf_token %}
              <!--<input type="hidden" name="csrfmiddlewaretoken" value="">-->
              <div class="form-group row my-3 p-3">
                <label for="id_old_password">
                   Старый пароль
                  <span class="required text-danger">*</span>
                </label>    
                <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль
                  <span class="required text-danger">*</span>
                </label>    
                <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                  <small id="id_new_password1-help" class="form-text text-muted">
                    <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                  </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля
                  <span class="required text-danger">*</span>
                </label>    
                <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Изменить пароль
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block main %}
{% load user_filters %}
<div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body"> 
            <form method="post" action="{% url 'users:password_reset_form' %}">
              {% csrf_token %}
              <!--<input type="hidden" name="csrfmiddlewaretoken" value="">-->
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>    
                <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сбросить пароль
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>  
  </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block main %}
<!--<div class="container py-5">-->
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
        {% load user_filters %} 
          {# Этот блок будет показан, если в форме есть ошибки #}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
<!--</div>-->
{% endblock %}